set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSROOT /opt/homebrew/Cellar/armv7-unknown-linux-gnueabihf/10.3.0/toolchain/armv7-unknown-linux-gnueabihf/sysroot/)
set(tools /opt/homebrew/bin)
set(CMAKE_C_COMPILER /opt/homebrew/bin/armv7-unknown-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER /opt/homebrew/bin/armv7-unknown-linux-gnueabihf-g++)
